name: "${project.name}"
version: ${project.version}
main: net.danh.dungeons.Dungeons
api-version: '1.13'
authors: [ VoChiDanh ]
depend:
  - PlaceholderAPI
softdepend:
  - MythicMobs
  - MMOItems
  - ItemEdit
commands:
  Dungeons:
    description: Main Commands